# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ppgNP-ke8qIEFfgL10rirD4phr5UpWU
"""

#importing libraries
import pandas as pd
import numpy as np

#Step-1: Load Dataset
df = pd.read_csv("/content/azure_based_raw_dataset.csv")
print(df)

#Step-2.1:Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Step-2.2:Standardize region names and ensure consistent format
df['region_name'] = (
    df['region_name'].str.strip().str.lower()
    .str.replace(" ", "-", regex=False)
)

df['region_name'] = df['region_name'].replace({
    'us-east': 'US-East',
    'us-west': 'US-West',
    'india-south': 'India-South',
    'india-west': 'India-West'
})
print(df)

#Step-2.3:Standardize service category
df['service_category'] = df['service_category'].str.lower().str.strip()

#Step-3:Remove Duplicate Records
duplicates = df.duplicated().sum()
print("Duplicate Records:", duplicates)
df = df.drop_duplicates()

#Step-4: Sorting dataset
df = df.sort_values(by=['region_name', 'service_category', 'timestamp'])
df = df.reset_index(drop=True)
print(df)

#Step-6: Handle missing values
df['actual_usage'] = df['actual_usage'].interpolate()
df['allocated_capacity'] = df['allocated_capacity'].interpolate()
df['actual_usage'] = np.minimum(df['actual_usage'],df['allocated_capacity'])
print(df)

#Step-6a: Learn cost per unit from valid rows only
valid = df[(df['operational_cost'].notna()) & (df['actual_usage'] > 0)].copy()

valid['cpu'] = valid['operational_cost'] / valid['actual_usage']

cost_map = valid.groupby(
    ['region_name','service_category']
)['cpu'].median()

#Step-6b: Map cost per unit back to main dataframe
df['cpu'] = df.set_index(
    ['region_name','service_category']
).index.map(cost_map)

#Step-6c: Fill missing operational cost using learned price
df['operational_cost'] = df['operational_cost'].fillna(
    df['actual_usage'] * df['cpu']
)

#Dropping helper column
df.drop(columns='cpu', inplace=True)

print(df)

#Step-6d:Forward fill service health
#(forward fill handles middle gaps backward fill fixes first-row gaps)
df['availability_ratio'] = df['availability_ratio'].ffill().bfill()

#Step-6e:Missing customer change assumed no movement
df['net_customer_change'] = df['net_customer_change'].fillna(0)

print(df)

#Step-6f:availability must be between 0–1
df['availability_ratio'] = df['availability_ratio'].clip(0.94, 0.999)

print("Missing values after cleaning:\n", df.isnull().sum())

df = df.sort_values(by='timestamp').reset_index(drop=True)

#Step-7:Cleaned dataset
df.to_csv("azure_based_cleaned_dataset.csv", index=False)