# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ppgNP-ke8qIEFfgL10rirD4phr5UpWU
"""
#Week 1
#importing libraries
import pandas as pd
import numpy as np

#Step-1: Load Dataset
df = pd.read_csv("/content/azure_based_raw_dataset.csv")
print(df)

#Step-2.1:Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Step-2.2:Standardize region names and ensure consistent format
df['region_name'] = (
    df['region_name'].str.strip().str.lower()
    .str.replace(" ", "-", regex=False)
)

df['region_name'] = df['region_name'].replace({
    'us-east': 'US-East',
    'us-west': 'US-West',
    'india-south': 'India-South',
    'india-west': 'India-West'
})
print(df)

#Step-2.3:Standardize service category
df['service_category'] = df['service_category'].str.lower().str.strip()

#Step-3:Remove Duplicate Records
duplicates = df.duplicated().sum()
print("Duplicate Records:", duplicates)
df = df.drop_duplicates()

#Step-4: Sorting dataset
df = df.sort_values(by=['region_name', 'service_category', 'timestamp'])
df = df.reset_index(drop=True)
print(df)

#Step-6: Handle missing values
df['actual_usage'] = df['actual_usage'].interpolate()
df['allocated_capacity'] = df['allocated_capacity'].interpolate()
df['actual_usage'] = np.minimum(df['actual_usage'],df['allocated_capacity'])
print(df)

#Step-6a: Learn cost per unit from valid rows only
valid = df[(df['operational_cost'].notna()) & (df['actual_usage'] > 0)].copy()

valid['cpu'] = valid['operational_cost'] / valid['actual_usage']

cost_map = valid.groupby(
    ['region_name','service_category']
)['cpu'].median()

#Step-6b: Map cost per unit back to main dataframe
df['cpu'] = df.set_index(
    ['region_name','service_category']
).index.map(cost_map)

#Step-6c: Fill missing operational cost using learned price
df['operational_cost'] = df['operational_cost'].fillna(
    df['actual_usage'] * df['cpu']
)

#Dropping helper column
df.drop(columns='cpu', inplace=True)

print(df)

#Step-6d:Forward fill service health
#(forward fill handles middle gaps backward fill fixes first-row gaps)
df['availability_ratio'] = df['availability_ratio'].ffill().bfill()

#Step-6e:Missing customer change assumed no movement
df['net_customer_change'] = df['net_customer_change'].fillna(0)

print(df)

#Step-6f:availability must be between 0–1
df['availability_ratio'] = df['availability_ratio'].clip(0.94, 0.999)

print("Missing values after cleaning:\n", df.isnull().sum())

df = df.sort_values(by='timestamp').reset_index(drop=True)

#Step-7:Cleaned dataset
df.to_csv("azure_based_cleaned_dataset.csv", index=False)

# Week-2
# Step-1: Convert timestamp column to proper datetime format
# This ensures correct time-based sorting and feature extraction

df["timestamp"] = pd.to_datetime(df["timestamp"])

# Step-2: Sort dataset by region, service, and time
# Sorting is mandatory before creating lag or rolling features
df = df.sort_values(by=['region_name', 'service_category', 'timestamp'])
# Reset index for clean sequential ordering after sorting
df = df.reset_index(drop=True)
print(df)

# Step-3: Extract time-based features (captures seasonality & behavioral patterns)
# Hour → intraday demand trends (The timestamp does not include hour, so no use of adding it)
# Day → daily variation
# Weekday → weekday vs weekend patterns

df["day"] = df["timestamp"].dt.day
df["weekday"] = df["timestamp"].dt.weekday
print(df)

# Step-4: Create Lag Features (captures historical memory)
# lag_1 → previous time period usage (short-term effect)
# lag_7 → weekly recurring pattern
df["lag_1_usage"] = df.groupby(
    ["region_name", "service_category"]
)["actual_usage"].shift(1)

df["lag_7_usage"] = df.groupby(
    ["region_name", "service_category"]
)["actual_usage"].shift(7)

print(df)

# Step-5: Rolling Mean Feature (captures smoothing & trend)
# 3-period rolling average per region-service group
# Helps reduce noise and highlight usage trend
df["rolling_mean_3"] = df.groupby(
    ["region_name", "service_category"]
)["actual_usage"].transform(lambda x: x.rolling(window=3).mean())

# Step-6: Detect Usage Spikes (Anomaly Indicator)
# A spike is defined as usage greater than mean + 1 standard deviation

threshold = df["actual_usage"].mean() + df["actual_usage"].std()
df["usage_spike"] = np.where(df["actual_usage"] > threshold, 1, 0)

# Step-7: Create Business Signal Feature
# customer_growth_flag = 1 if net customers increased
# Converts numeric growth into binary business indicator
df["customer_growth_flag"] = np.where(
    df["net_customer_change"] > 0, 1, 0
)

# Step-9: Encode categorical variables for machine learning
# Converts region_name and service_category(compute as 0) into numeric dummy variables
# drop_first=True prevents multicollinearity (dummy variable trap)
df = pd.get_dummies(df,columns=["region_name", "service_category"],drop_first=True,dtype=int)

print(df)

print("Final Dataset Shape:", df.shape)
print(df.head())

#Step-7:Processed dataset
df.to_csv("azure_based_processed_dataset.csv", index=False)
